# Generated by Django 5.2.8 on 2025-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BJJPos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pt', models.TextField(db_column='nome_pt')),
                ('nome_en', models.TextField(db_column='nome_en')),
                ('categoria', models.TextField(db_column='categoria')),
                ('dificuldade', models.TextField(db_column='dificuldade')),
                ('descricao', models.TextField(db_column='descricao')),
                ('observacoes', models.TextField(db_column='observacoes')),
            ],
            options={
                'db_table': 'posicoes',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
